# Generated by Django 5.0.1 on 2024-03-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
