# Generated by Django 5.0.1 on 2024-03-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
